import "./globals.css";
import Navigation from "@/components/Navigation";
import { AppProvider } from "@/contexts/AppContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col w-screen h-screen">
        <AppProvider>
          <Navigation />
          {children}
        </AppProvider>
        <Toaster />
      </body>
    </html>
  );
}
